name: Build Spring Petclinic with JFrog Artifactory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - 
        name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      -
        name: Run Maven build
        run: |
          jf mvn-config --repo-resolve-releases fg-maven --repo-resolve-snapshots fg-maven --repo-deploy-releases fg-maven-local-releases --repo-deploy-snapshots fg-maven-local-snapshots
          jf mvn clean deploy -Dtest=!PostgresIntegrationTests* --project fg
          jf rt build-publish --project fg
      -
        name: Publish build information to Artifactory
        run: |
          jf rt build-publish --project fg
      -
        name: Build Docker image
        run: |
          jf docker build -t soleng.jfrog.io/fg-docker/spring-petclinic:3.1.0-SNAPSHOT --build-arg petclinicArtifact=./target/spring-petclinic-3.1.0-SNAPSHOT.jar .
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: spring-petclinic:3.1.0-SNAPSHOT
          build-args: petclinicArtifact=./target/spring-petclinic-3.1.0-SNAPSHOT.jar
